/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication5;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javaapplication5.ServerConf.valuehost;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author inv.Desarrollo2
 */
public final class NewJFrame extends javax.swing.JFrame implements Runnable{
Connectionns conexion =new Connectionns();
 LoginDialog loginDalog = new LoginDialog();
ServerConf  Frameconf=new ServerConf();
Files readFile=new Files();
String[] items=new String[1];
String propertyfile,val1,val2,val3,val4;
String modelo,orden,so;
String[] result;
Thread thread =new Thread();
boolean bool;
int login;

   /**
     * Creates new form NewJFrame
     * @throws javax.xml.parsers.ParserConfigurationException
     * @throws org.xml.sax.SAXException
     * @throws java.io.IOException
     * @throws java.lang.InterruptedException
     */
    public NewJFrame() throws ParserConfigurationException, SAXException, IOException, InterruptedException {

        initComponents();
        //readFile.Readxml(this,items);

//         if( readFile.Readxml(this,items,"server")!=""){
//         
//               Split(readFile.Readxml(this,items,"server"));  
//        
//        if(!conexion.connectDB(this,val1,val2,val3,val4)){
//                   try {
//                       System.out.println("connected");
//                       
//                       Split(readFile.Readxml(this,items,"equipo"));
//                       
//                 // readFile.execCmd(jTextArea1,"C:\\Users\\desarrollo06\\Desktop\\validate.bat");
//                  
//                   } catch (Exception ex) {
//                       Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
//                   }
//    
//        
//        }
//        else{ System.out.println("invalid connect");
//        System.exit(0);
//        }        
//         }
//         else{
//          JOptionPane.showMessageDialog(this,"parametros invalidos en host.xml", null, 0);
//         System.exit(0);
//         }
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
               
        
        if(!conexion.connectDB(this,Frameconf.preferences.get(Frameconf.prefnamehost, valuehost),
                Frameconf.preferences.get(Frameconf.prefnameDB, Frameconf.valuedb),
                Frameconf.preferences.get(Frameconf.prefnameuser, Frameconf.valueuser),
                Frameconf.preferences.get(Frameconf.prefnamepass, Frameconf.valuepass))){
                   try {
                       System.out.println("connected");
                       
                       Split(readFile.Readxml(this,items,"equipo"));
                       
                 // readFile.execCmd(jTextArea1,"C:\\Users\\desarrollo06\\Desktop\\validate.bat");
                  
                   } catch (Exception ex) {
                       Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                   }
    
        
        }
         else{
          JOptionPane.showMessageDialog(this,"parametros invalidos", null, 0);
        jTextArea1.setText(conexion.getError());
        }
               //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//  Split(readFile.Readxml(this,items,"server"));  
//        conexion.connectDB(this,val1,val2,val3,val4); 
       //ystem.out.print(readFile.Readxml(this,items));ammm 
//System.out.println(readFile.getReg("SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion","ProductName"));


    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        jMenu1.setText("configuración");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("login");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("servidor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("orden");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ServerConf frameconf = new ServerConf();
        frameconf.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      OrdenConf ordenConf = new OrdenConf();
        ordenConf.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
     // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new NewJFrame().setVisible(true);
                } catch (        ParserConfigurationException | SAXException | IOException | InterruptedException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
    }
    public void Split(String strsplit){
int i=0;

        result = strsplit.split(";;");

        for(String s : result){
            System.out.println(s);
            switch(i){
                     case 0:val1=s.toString();
                    break;
                     case 1:val2=s.toString();
                    break;
                     case 2:val3=s.toString();
                    break;
                     case 3:val4=s.toString();
                    break;
            }
            i++;
        }
    }
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.

    }

}
